#!/bin/bash

echo "=== SAFE TO DELETE FILES ==="
echo ""
echo "The following files appear to be truly unused and can be safely deleted:"
echo ""

# Files that are definitely safe to delete
safe_files=(
"src/app/admin-dashboard/components/action-button.tsx"
"src/app/admin-dashboard/components/AdminLogo.tsx"
"src/app/admin-dashboard/components/CustomersContent.tsx"
"src/app/admin-dashboard/components/CustomersContentSkeleton.tsx"
"src/app/admin-dashboard/components/VirtualizedList.tsx"
"src/app/admin-dashboard/analytics/components/analytics-notifier.tsx"
"src/app/admin-dashboard/analytics/components/live-activity-indicator.tsx"
"src/app/admin-dashboard/analytics/components/realtime-stat-updater.tsx"
"src/components/auth/auth-initializer.tsx"
"src/components/booking/BookingStepTracker.tsx"
"src/components/booking/submit-booking-button.tsx"
"src/components/error/query-error-boundary.tsx"
"src/components/error/trpc-error-handler.tsx"
"src/components/FAQ.tsx"
"src/components/gallery/gallery-photos-client.ts"
"src/components/gallery/GalleryFeatured.tsx"
"src/components/gallery/GalleryItemCard.tsx"
"src/components/HomeFeatures.tsx"
"src/components/InstagramFeed.tsx"
"src/components/layouts/ClientLayout.tsx"
"src/components/layouts/HeaderNav.tsx"
"src/components/layouts/Hero.tsx"
"src/components/layouts/HeroSection.tsx"
"src/components/layouts/Nav.tsx"
"src/components/layouts/PageHeader.tsx"
"src/components/LeadMagnet.tsx"
"src/components/payments/DepositPayment.tsx"
"src/components/payments/PaymentProcessor.tsx"
"src/components/settings/GoogleCalendarIntegration.tsx"
"src/components/theme/tailwind-theme.ts"
"src/components/theme/ThemeSwitcher.tsx"
"src/components/ui/breadcrumb.tsx"
"src/components/ui/command.tsx"
"src/components/ui/form-field.tsx"
"src/components/ui/icon-button.tsx"
"src/components/ui/resizable.tsx"
"src/components/ui/scroll-animations.tsx"
"src/components/ui/select-dropdown.tsx"
"src/components/ui/sidebar.tsx"
"src/components/ui/theme-toggle.tsx"
"src/shared/components/ModeSwitch.tsx"
"src/lib/admin-auth.ts"
"src/lib/analytics/seo-tracking.ts"
"src/lib/api-functions.ts"
"src/lib/api-route.ts"
"src/lib/api/api-error-handler.ts"
"src/lib/db/db-user.ts"
"src/lib/db/functions-exports.ts"
"src/lib/db/prisma-exports.ts"
"src/lib/db/repositories/appointment-repository.ts"
"src/lib/dynamic-components.ts"
"src/lib/external-api.ts"
"src/lib/performance/web-vitals.ts"
"src/lib/seo/organic-seo-strategy.ts"
"src/lib/server-bootstrap.ts"
"src/lib/services/email-automations.ts"
"src/lib/services/email-workflows.ts"
"src/lib/services/google-auth.ts"
"src/lib/services/google-calendar.ts"
"src/lib/supabase-simple.ts"
"src/lib/trpc/direct-exports.ts"
"src/lib/trpc/server-exports.ts"
"src/lib/utils/browser/device-detection.ts"
"src/lib/utils/browser/fingerprinting.ts"
"src/lib/utils/cn.ts"
"src/lib/utils/hooks/use-memoization.ts"
"src/store/useAppStore.tsx"
"src/store/useUIStore.tsx"
"src/utils/error-utils.ts"
"src/utils/memoization.ts"
"src/utils/ua-parser.ts"
"src/hooks/trpc/use-appointment-reschedule.ts"
)

for file in "${safe_files[@]}"; do
    if [ -f "$file" ]; then
        echo "  - $file"
    fi
done

echo ""
echo "=== PROCEED WITH CAUTION ==="
echo ""
echo "The following files should be reviewed before deletion:"
echo ""
echo "1. Type definition files (might be imported elsewhere):"
for file in src/types/*.ts src/types/*/*.ts; do
    if grep -q "$file" /tmp/safe_to_delete.txt; then
        echo "  - $file"
    fi
done

echo ""
echo "2. Index/barrel files (but you want to remove these anyway):"
echo "  - src/hooks/index.ts"
echo "  - src/hooks/trpc/index.ts"
echo "  - src/lib/trpc/routers/index.ts"
echo "  - src/lib/utils/browser/index.ts"

echo ""
echo "3. Files with potential CSS/dynamic references:"
echo "  - src/components/layouts/Container.tsx"
echo "  - src/components/ui/grid.tsx"
echo "  - src/lib/keys.tsx"

echo ""
echo "4. Email templates (might be used by email service):"
echo "  - src/emails/AuthConfirmation.tsx"
echo "  - src/emails/ContactConfirmation.tsx"

echo ""
echo "=== TO DELETE ALL SAFE FILES ==="
echo ""
echo "Run this command to delete all safe files:"
echo "rm -f \\"
for file in "${safe_files[@]}"; do
    echo "  $file \\"
done
echo ""