-- Fix CRM views to use camelCase naming convention
-- Generated by scripts/update-sql-views.js

-- Drop old views
DROP VIEW IF EXISTS campaign_recipients;
DROP VIEW IF EXISTS tattoo_designs;
DROP VIEW IF EXISTS appointments_summary;
DROP VIEW IF EXISTS appointments;
DROP VIEW IF EXISTS clients_summary;
DROP VIEW IF EXISTS customers;

-- Create updated views
CREATE OR REPLACE VIEW "customers" AS SELECT
  id,
  "firstName" AS firstName,
  "lastName" AS lastName,
  email,
  phone,
  "avatarUrl" as avatar_url,
  address,
  city,
  state,
  "postalCode" AS postalCode,
  country,
  "birthDate" AS birthDate,
  notes,
  allergies,
  source,
  tags,
  "createdAt" AS createdAt,
  "updatedAt" AS updatedAt
FROM "Customer";

CREATE OR REPLACE VIEW "clients_summary" AS SELECT
  id,
  "firstName" AS firstName,
  "lastName" AS lastName,
  email,
  phone,
  "avatarUrl" as avatar_url,
  address,
  city,
  state,
  "postalCode" AS postalCode,
  country,
  "birthDate" AS birthDate,
  notes,
  allergies,
  source,
  tags,
  "createdAt" AS createdAt,
  "updatedAt" AS updatedAt,
  CONCAT("firstName", ' ', "lastName") AS fullName
FROM "Customer";

CREATE OR REPLACE VIEW "appointments" AS SELECT
  a.id,
  a.title,
  a.description,
  a."startDate" AS startTime,
  a."endDate" AS endTime,
  a.status,
  a.deposit,
  a.deposit > 0 AND a.status = 'confirmed' AS depositPaid,
  a."totalPrice" AS totalPrice,
  a."designNotes" AS designNotes,
  a.location,
  a."followUpDate" AS followUpDate,
  a."createdAt" AS createdAt,
  a."updatedAt" AS updatedAt,
  a."customerId" AS customerId,
  a."artistId" as artist_id
FROM "Appointment" a;

CREATE OR REPLACE VIEW "appointments_summary" AS SELECT
  a.id,
  a.title,
  a.description,
  a."startDate" AS startTime,
  a."endDate" AS endTime,
  a.status,
  a.deposit,
  a.deposit > 0 AND a.status = 'confirmed' AS depositPaid,
  a."totalPrice" AS totalPrice,
  a."designNotes" AS designNotes,
  a.location,
  a."followUpDate" AS followUpDate,
  a."createdAt" AS createdAt,
  a."updatedAt" AS updatedAt,
  a."customerId" AS customerId,
  CONCAT(c."firstName", ' ', c."lastName") AS customerName,
  c.email AS customerEmail,
  c.phone AS customerPhone,
  a."artistId" as artist_id,
  u.name as artist_name,
  u.email as artist_email
FROM "Appointment" a
LEFT JOIN "Customer" c ON a."customerId" = c.id
LEFT JOIN "Artist" art ON a."artistId" = art.id
LEFT JOIN "User" u ON art."userId" = u.id;

CREATE OR REPLACE VIEW "tattoo_designs" AS SELECT
  id,
  name as title,
  description,
  "fileUrl" as file_url,
  "thumbnailUrl" as thumbnail_url,
  "designType" as design_type,
  size,
  "isApproved" as is_approved,
  "approvedAt" as approved_at,
  "createdAt" AS createdAt,
  "updatedAt" AS updatedAt,
  "artistId" as artist_id,
  "customerId" AS customerId
FROM "TattooDesign";

CREATE OR REPLACE VIEW "campaign_recipients" AS SELECT
  c.id,
  c.email,
  CONCAT(c."firstName", ' ', c."lastName") as name,
  c.tags,
  c."createdAt" AS createdAt,
  c."updatedAt" AS updatedAt,
  NULL as campaign_id,
  NULL as sent_at,
  NULL as opened_at,
  NULL as clicked_at,
  'pending' as status
FROM "Customer" c
WHERE c.email IS NOT NULL;

