/**
 * Core types for the application
 * Only types that are NOT generated by Prisma should be here
 * All database models and enums come from @prisma/client
 */

// ============================================================================
// API Request/Response Types (not database entities)
// ============================================================================

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    hasMore?: boolean;
  };
}

export interface ApiError {
  message: string;
  code?: string;
  status?: number;
}

// ============================================================================
// Form Data Types (for form submissions, not database models)
// ============================================================================

export interface BookingFormData {
  name: string;
  email: string;
  phone: string;
  tattooType: string;
  size: string;
  placement: string;
  description: string;
  preferredDate: string;
  preferredTime: string;
  agreeToTerms: boolean;
  referenceImages?: string[];
  paymentMethod?: string;
}

export interface ContactFormData {
  name: string;
  email: string;
  subject: string;
  message: string;
  agreeToTerms: boolean;
}

// ============================================================================
// UI Component Props (not database related)
// ============================================================================

export interface MetricCardProps {
  title: string;
  value: string | number;
  change?: number;
  trend?: 'up' | 'down' | 'neutral';
  icon: React.ReactNode;
  description?: string;
  href?: string;
  className?: string;
}

export interface ServiceCardProps {
  service: {
    id: string;
    title: string;
    description: string;
    image: string;
    features: string[];
  };
  index?: number;
}

// ============================================================================
// External API Types (Cal.com webhook payloads, etc.)
// ============================================================================

export interface CalWebhookPayload {
  triggerEvent: string;
  createdAt: string;
  payload: {
    id: number;
    uid: string;
    title: string;
    startTime: string;
    endTime: string;
    status: string;
    attendees: Array<{
      email: string;
      name: string;
      timeZone: string;
    }>;
  };
}

// ============================================================================
// Business Logic Types (calculations, not stored in DB)
// ============================================================================

export interface PricingBreakdown {
  baseHourlyRate: number;
  estimatedHours: number;
  sizeFactor: number;
  placementFactor: number;
  complexityFactor: number;
  totalPrice: number;
  depositAmount: number;
}

// ============================================================================
// Utility Types
// ============================================================================

export type DateRange = {
  startDate: Date;
  endDate: Date;
};

export type ID = string | number;
