import {
AlertTriangle,
ArrowRight,
Check,
ChevronLeft,
ChevronRight,
Command,
CreditCard,
File,
FileText,
HelpCircle,
Image,
ImageOff,
Laptop,
Loader2,
LogOut,
Mail,
Moon,
MoreVertical,
Pizza,
Plus,
RefreshCw,
Settings,
SunMedium,
Trash,
Twitter,
User,
X,
Instagram,
Facebook,
Github,
Chrome,
MessageCircle,
type Icon,
} from 'lucide-react';

export type { Icon };

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  logout: LogOut,
  mail: Mail,
  refresh: RefreshCw,
  imageOff: ImageOff,
  google: Chrome,
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  gitHub: Github,
  check: Check,
  discord: MessageCircle,
  file: File,
  fileText: FileText,
  image: Image,
};
